name: Bubble Merge
on:
  issue_comment:
    types: [created, edited]
    branches-ignore:
      - master

jobs:
  bubble_merge:
    name: Bubble Merge
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '@squiddy-bot merge')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.SQUIDDY_BOT_GITHUB_TOKEN }}
      - name: Acknowledge Failure
        if: ${{ failure() }}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.SQUIDDY_BOT_GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Rebase was not possible. Please rebase manually and try again.'
            })
      - uses: futurelearn/squiddy/actions/bubble_merge@master
        env:
          GITHUB_TOKEN: ${{ secrets.SQUIDDY_BOT_GITHUB_TOKEN }}
          GITHUB_EVENT: ${{ toJson(github.event) }}
