name: Bubble Merge
on:
  issue_comment:
    types: [created, edited]

jobs:
  bubble_merge:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '@squiddy-bot merge')
    name: Bubble Merge
    uses: futurelearn/actions/.github/workflows/bubble_merge.yaml@main
    secrets:
      SQUIDDY_BOT_GITHUB_TOKEN: ${{ secrets.SQUIDDY_BOT_GITHUB_TOKEN }}
