name: Test and build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: branch_name
      run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle exec rspec
    - uses: docker/build-push-action@v1
      if: steps.branch_name.outputs.branch != 'master'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache_froms: futurelearn/squiddy:latest
        repository: futurelearn/squiddy
        tags: ${{ steps.branch_name.outputs.branch }}
    - uses: docker/build-push-action@v1
      if: steps.branch_name.outputs.branch == 'master'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache_froms: futurelearn/squiddy:latest
        repository: futurelearn/squiddy
        tags: latest
    - name: Build gem
      if: steps.branch_name.outputs.branch == 'master'
      run: |
        echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        gem build squiddy.gemspec
        gem push --key github --host https://rubygems.pkg.github.com/futurelearn squiddy-$(cat VERSION).gem || true
